apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-plugin
  namespace: kubevirt-plugin
  labels:
    app: kubevirt-plugin
    app.kubernetes.io/component: kubevirt-plugin
    app.kubernetes.io/instance: kubevirt-plugin
    app.kubernetes.io/part-of: kubevirt-plugin
    app.openshift.io/runtime-namespace: kubevirt-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-plugin
  template:
    metadata:
      labels:
        app: kubevirt-plugin
    spec:
      containers:
        - name: kubevirt-plugin
          image: quay.io/vszocs/kubevirt-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: kubevirt-plugin
  namespace: kubevirt-plugin
  labels:
    app: kubevirt-plugin
    app.kubernetes.io/component: kubevirt-plugin
    app.kubernetes.io/instance: kubevirt-plugin
    app.kubernetes.io/part-of: kubevirt-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: kubevirt-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: kubevirt-plugin
spec:
  displayName: 'OpenShift Console Demo Plugin'
  service:
    name: kubevirt-plugin
    namespace: kubevirt-plugin
    port: 9001
    basePath: '/'
  proxy:
    services:
      - name: thanos-querier
        namespace: openshift-monitoring
        port: 9091
        authorize: true
