name: Node CI
on: [push]
jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint # will run `yarn lint` command
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command