name: PR
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        id: automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'approved,lgtm,!WIP,!hold'
          MERGE_METHOD: squash
            
      - name: Merge Comment
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '
                  ✨PR Status ✨
                  | Condition |  |
                  | ------------- | ------------- |
                  | Has Required Labels `approved, lgtm` | ${{ contains( github.event.pull_request.labels.*.name, 'approved') &&
                    contains( github.event.pull_request.labels.*.name, 'lgtm') && '✅' || '❌' }} |
                  | No Blocking Labels `wip, hold` | ${{ (contains( github.event.pull_request.labels.*.name, 'wip') ||
                    contains( github.event.pull_request.labels.*.name, 'hold')) && '❌' || '✅' }} |
                    
                    _This Pull Request will not merge until all required tests have passed_
              '
            })
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: "${{ secrets.BOT_PAT }}"
          header: 'pr-status'
          delete: true
          message: |
            ✨PR Status ✨
            | Condition |  |
            | ------------- | ------------- |
            | Has Required Labels `approved, lgtm` | ${{ contains( github.event.pull_request.labels.*.name, 'approved') &&
              contains( github.event.pull_request.labels.*.name, 'lgtm') && '✅' || '❌' }} |
            | No Blocking Labels `wip, hold` | ${{ (contains( github.event.pull_request.labels.*.name, 'wip') ||
              contains( github.event.pull_request.labels.*.name, 'hold')) && '❌' || '✅' }} |
              
              _This Pull Request will not merge until all required tests have passed_
 