name: PR
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        id: automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'approve,lgtm,!WIP,!hold'
          MERGE_METHOD: squash
      
      - name: Merge Status
        env:
          MERGE_OUTPUT: '${{ toJSON(steps.automerge.outputs) }}'
        run: echo "merge $MERGE_OUTPUT"