name: PR
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      !contains( github.event.pull_request.labels.*.name, 'hold') &&
      !contains( github.event.pull_request.labels.*.name, 'WIP') &&
      contains( github.event.pull_request.labels.*.name, 'approved') &&
      contains( github.event.pull_request.labels.*.name, 'lgtm')
    steps:
      - name: Automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
