name: CI
on: [pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Unit Testing
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test-cov