name: PR
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  status-comment:
    runs-on: ubuntu-latest
    steps:     
      - name: Merge Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            PR Status
            - Has required labels `approved, lgtm` - ${{ contains( github.event.pull_request.labels.*.name, 'approved') &&
              contains( github.event.pull_request.labels.*.name, 'lgtm') && '✅' || '❌' }}
            - No blocking labels `wip, hold` - ${{ (contains( github.event.pull_request.labels.*.name, 'wip') ||
              contains( github.event.pull_request.labels.*.name, 'hold')) && '❌' || '✅' }}
              
              _This Pull Request will not merge until all required tests passed_
 