name: PR
on:
  pull_request:
    types:
      - opened
jobs:
  contrib_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: console.log(context)
