name: PR
on:
  pull_request:
    types:
      - opened
jobs:
  contrib_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the contribution!'
            })
