name: PR
on:
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types: [created, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Approvers
        id: approvers
        run: echo ::set-output name=approvers::$(cat ./OWNERS)

      - name: Add Approve label
        if: |
          contains(github.event.comment.html_url, '/pull/') &&
          (contains(github.event.comment.body, '/approve') || contains(github.event.comment.body, '/lgtm')) &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          add-labels: 'approved'

      - name: Add LGTM label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/lgtm') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null') &&
          github.event.issue.user.login != github.event.comment.user.login
        uses: andymckay/labeler@master
        with:
          add-labels: 'lgtm'
          remove-labels: 'WIP'

      - name: Add WIP label / comment trigger
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip')
        uses: andymckay/labeler@master
        with:
          add-labels: 'WIP'

      - name: Add WIP label / title trigger
        if: |
          contains(github.event.pull_request.title, 'wip') ||
          contains(github.event.pull_request.title, 'WIP')
        uses: andymckay/labeler@master
        with:
          add-labels: 'WIP'

      - name: Remove WIP label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/remove wip')
        uses: andymckay/labeler@master
        with:
          remove-labels: 'WIP'

      - name: Add Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/hold') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          add-labels: 'hold'

      - name: Remove Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/remove hold') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          remove-labels: 'hold'

      - name: Add Bug label / title trigger
        if: |
          contains(github.event.pull_request.title, 'bug') ||
          contains(github.event.pull_request.title, 'BUG')
        uses: andymckay/labeler@master
        with:
          add-labels: 'bug'
