name: CI
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check for /lgtm comment
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/lgtm'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Add LGTM label
        if: steps.check.outputs.triggered == 'true'
        uses: andymckay/labeler@master
        with:
          add-labels: "approved, lgtm"