name: PR
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
        steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assign author to PR
        uses: technote-space/assign-author@v1

      - name: Request review
        uses: uesteibar/reviewer-lottery@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
