name: CI
on:
  pull_request:
    types: [ labeled ]
jobs:
  merge:
    name: merge
    if: |
      github.event.check_suite.status == 'completed' &&
      contains(github.event.pull_request.labels.*.name, 'approved') &&
      contains(github.event.pull_request.labels.*.name, 'lgtm')
    runs-on: ubuntu-latest

    steps:
    - name: "Merge pull request"
      uses: "actions/github-script@v2"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          const pullRequest = context.payload.pull_request
          const repository = context.repo

          await github.pulls.merge({
            merge_method: "merge",
            owner: repository.owner,
            pull_number: pullRequest.number,
            repo: repository.repo,
          })