name: TEST
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  issue_comment:
    types: [created, edited]
  check_suite:
    types:
      - completed
jobs:
  envtest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Approvers
        id: approvers
        run: echo ::set-output name=approvers::$(cat ./OWNERS)
      - name: Test output
        run: echo ${{ steps.approvers.outputs.approvers }}
